---

sudo: true
language: python

matrix:
    allow_failures:
        - python: nightly
        - python: 3.7-dev
    include:
        - os: linux
          dist: bionic
          python: nightly
        - os: linux
          dist: bionic
          python: 3.7-dev
        - os: linux
          dist: xenial
          python: 3.7
        #- os: linux
        #  dist: 
        #  python: 3.6            # = min required version for Emma
        # Disabled since travis does not support python on windows
        # - os: windows

install:
    - sudo apt-get install tree
    - pip install -U pylint
    - sudo apt-get install enchant          # needed for pyenchant
    - pip install pyenchant                 # needed for pylint spell checking
    - pip install -U coveralls
    - pip install codacy-coverage
    - pip install -U Pygments Markdown matplotlib pandas pypiscout
    - sudo apt-get update
    - sudo apt-get install graphviz
    - pip install -U gprof2dot
    - pip list

git:
    submodules: false

script:
    - tree --charset unicode ../../
    - find . -type f -name "*.py" -exec pylint -j 0 --exit-zero {} \;
    - python -m unittest test
    - pushd ./tests
    - coverage run --branch test__cmd-line.py
    - tree -a -I .git ../
    - coverage report
    - coverage xml

after_success:
    - python-codacy-coverage -r coverage.xml

