---

sudo: true
language: python

python:
    #- 3.7-dev
    - 3.7.0

matrix:
    include:
        - os: linux
          dist: bionic
        # Disabled since travis does not support python on windows
        # - os: windows

install:
    - pip install -U pylint
    - sudo apt-get install myspell-de-de myspell-en-gb
    - pip install -U coveralls
    - pip install -U Pygments Markdown matplotlib pandas pypiscout
#    - sudo apt-get update
#    - sudo apt-get install graphviz
#    - pip install -U gprof2dot
    - pip list

git:
    submodules: false

script:
    - python -m unittest test
    - pylint -j 0 --exit-zero ./*
    - cd tests
    - coverage run --branch test__cmd-line.py
    - coverage report

after_success:
    - coveralls
