---

sudo: true
language: python

matrix:
    allow_failures:
        - python: nightly
        - python: 3.7-dev
    include:
        - os: linux
          dist: bionic
          python: nightly
          
        - os: linux
          dist: bionic
          python: 3.7-dev
        - os: linux
          dist: xenial
          python: 3.7
          env: CODE_COV=true                # Only do code coverage once
        - os: linux
          dist: xenial
          python: 3.6            # = min required version for Emma
        # Disabled since travis does not support python on windows
        # - os: windows

install:
    # General packages
    - sudo apt-get install tree
    - pip install -U pylint
    - sudo apt-get install enchant          # needed for pyenchant
    - pip install pyenchant                 # needed for pylint spell checking
    - pip install -U coveralls
    - pip install codacy-coverage
    # Packages for Emma
    - pip install -U Pygments Markdown matplotlib pandas pypiscout graphviz
    # Packages for Emma reports + html doc
    - sudo apt-get update
    - sudo apt-get install graphviz
    - pip install -U gprof2dot
    # List installed pip packages
    - pip list

git:
    submodules: false

script:
    - tree -a -I .git ../
    - find . -type f -name "*.py" -exec pylint -j 0 --exit-zero {} \;
    - cd tests/functional_tests
    - python -m unittest -v
    - cd ../unit_tests
    - coverage run -m unittest -v
    - tree -a -I .git ../
    - coverage report --omit="/home/travis/virtualenv/*","/home/travis/build/bmwcarit/Emma/tests/*"
    - coverage xml

after_success:
    - if [ -n "$CODE_COV" ]; then python-codacy-coverage -r coverage.xml; else echo skip; fi
