---

sudo: true
language: python

#env:
#  global:
#    - LINUX_MAIN_DIST=xenial
#    - PYTHON_MAIN_VERSION=3.7

allow_failures:
    - python: nightly
    - python: 3.7-dev

git:
    submodules: false

.ci-matrix-definitions:
    - &linux-bionic-nightly
      os: linux
      dist: bionic
      python: nightly

    - &linux-bionic-3-7-dev
      os: linux
      dist: bionic
      python: 3.7-dev

    - &linux-bionic-3-7
      os: linux
      dist: xenial
      python: 3.7
      env: CODE_COV=true                # Only do code coverage once
    - &linux-xenial-3-6
      os: linux
      dist: xenial
      python: 3.6            # = min required version for Emma
    # Disabled since travis does not support python on windows
    # - os: windows

install:
    # General packages
    - sudo apt-get install tree
    - pip install -U pylint
    - sudo apt-get install enchant          # needed for pyenchant
    - pip install pyenchant                 # needed for pylint spell checking
    - pip install -U coveralls
    - pip install codacy-coverage
    # Packages for Emma
    - pip install -U Pygments Markdown matplotlib pandas pypiscout graphviz
    # Packages for Emma reports + html doc
    - sudo apt-get update
    - sudo apt-get install graphviz
    - pip install -U gprof2dot
    # Install pip deployment packages
    - pip install --upgrade setuptools
    - pip install --upgrade wheel
    - pip install --upgrade twine
    # List installed pip packages
    - pip list

.emma-testing-script:
    - &emma-tests
        - cd tests/functional_tests
        - python -m unittest -v
        - cd ../unit_tests
        - cd ..
    - &emma-deploy
        - tree -a -I .git ../
        - cd tests/functional_tests
        - python -m unittest -v
        - cd ../unit_tests
        - cd ..
        - tree -a -I .git ../

# TODO: add alias + anchor for script in testing stage (MSc)
jobs:
    include:
#        - stage: testing
#          <<: *linux-xenial-3-6
#          script: *emma-tests
#        - stage: testing
#          <<: *linux-bionic-3-7
#          script: *emma-tests
#        - stage: testing
#          <<: *linux-bionic-3-7-dev
#          script: *emma-tests
#        - stage: testing
#          <<: *linux-bionic-nightly
#          script: *emma-tests
#
#        - stage: linting
#          <<: *linux-bionic-3-7
#          script:
#              - tree -a -I .git ../
#              - find . -type f -name "*.py" -exec pylint -j 0 --exit-zero {} \;
#
#        - stage: coverage
#          <<: *linux-bionic-3-7
#          script:
#              - coverage run -m unittest -v
#              - tree -a -I .git ../
#              - coverage report --omit="/home/travis/virtualenv/*","/home/travis/build/bmwcarit/Emma/tests/*"
#              - coverage xml

        - stage: deployment
          <<: *linux-bionic-3-7
#          script: *emma-deploy
          deploy:
              provider: pypi
              server: https://test.pypi.org/legacy/
              user: holzkohlengrill
              password:
                  secure: deeDX2CmOp9H07QCgRRKAT8QBfHs3ZqE9kvpM1102+eelUWxiIkiuU5ewZXCCbMRumRvSLFUd4SZB+lQYs3svB4AVF2/u5NrcN5H+7Z0nczQeuXzdiZt8DY+lU3J2Va8VYNt5Gdj7wEie42ZqZRsYSZcV6emKUb8IxlxNFlGHe3ZgkTegPu4DlmWPnCLxe978LdKsTa4O/D/270AT0j7tYURTnnt1bNBnZXWHpli61bveAFkuJ5wwPYTh3eUWG02Oe3/ePEJIhErR5AhpQd5Xi4m0CFWh/P9RDvem3ySnU3xP4AK2qP3pGbw+IWnIYlXZAWu7YAuARgguI9yvyCRZlJFbMg3NXpXBUDWovD2A2tw/uxhnd3SR0jM3eCHluA0pSKUd3BHWkvOF0CR0hyLslnHvIX/IrnYLHhECqAqJESjxAYDz1OQY6f7b2INRU98BZkhXIYofch7bCfVXpGi8gR//840FTRP80mlGNB0J3wti8l5eoJTCiXO0mhzfGOQaegNDNlvfwse7rQXtka4GRlaNbQ3sLlkV80PA5bUn0U255lH6eH29kVQQnT0rUs6f2HID8HM6eiqdcKZ0mrVmIRO22dxQQoqOOiFboeLHCX8islvGT96yTubFEqVEnTRa/er+qCJjZUGEIqo9WHJAQEgXSU0MCMRrTLQ6DrMTog=
              distributions: "sdist bdist_wheel"          # add `bdist_wheel` besides `sdist`
              on:
                  branch: 18-pip-database
#                    tags: true
              after: tree -a -I .git ../
